version: '3.1'

services:
    controller:
        image: unifi-controller
        ports:
            - 8443:8443
            - 8080:8080
        deploy:
            restart_policy:
                condition: always
