version: '3.1'

services:
    mariadb:
        image: mariadb
        deploy:
            restart_policy:
                condition: on-failure
        environment:
            MYSQL_ROOT_PASSWORD: example
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        depends_on:
            - mariadb
        networks:
            - traefik-net
        deploy:
            restart_policy:
                condition: any
            labels:
                - traefik.port=8080
                - traefik.frontend.rule=Host:phpmyadmin.airwarrior.net

networks:
    traefik-net:
        external: true
