version: '3.1'

services:
    db:
        image: mariadb
        deploy:
            restart_policy:
                condition: on-failure
        environment:
            MYSQL_ROOT_PASSWORD: example
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        deploy:
            restart_policy:
                condition: on-failure
            labels:
                - traefik.port=8080
                - traefik.frontend.rule=Host:phpmyadmin.airwarrior.net
