version: '3.1'

services:
    mariadb:
        image: mariadb
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: example
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        depends_on:
            - mariadb
        networks:
            - traefik-net
        restart: always
        labels:
            - traefik.port=80
            - traefik.frontend.rule=Host:phpmyadmin.airwarrior.net
            - traefik.frontend.auth.basic=admin:$$apr1$$LbMpDV.H$$KOhjvjaXRpztOwF9LgHCa0

networks:
    traefik-net:
        external: true
