# Run the following command from the cli to create the traefik network
# docker network create --driver=overlay traefik-net
version: "3"
services:
    traefik:
        image: traefik
        ports:
            - 8081:8080
            - 80:80
            - 443:443
        networks:
            - traefik-net
        deploy:
#            labels:
#                - traefik.port=8080
#                - traefik.frontend.rule=Host:traefik.alyrica.net
            restart_policy:
                condition: on-failure
            mode: replicated
            replicas: 1
            placement:
                constraints:
                    - "node.role==manager"
        volumes:
#            - /docker/data/traefik:/etc/traefik
            - /var/run/docker.sock:/var/run/docker.sock
            - /usr/local/etc/ssl/current:/ssl
        command:
            - --web
            - --docker
#            - --docker.swarmmode
            - --docker.domain=airwarrior.net
            - --docker.watch
            - --entrypoints=Name:http Address::80 Redirect.EntryPoint:https
            - --entrypoints=Name:https Address::443 TLS:/ssl/cert.pem,/ssl/key.pem
            - --defaultentrypoints=http,https
networks:
    traefik-net:
        external: true
