# Run the following command from the cli to create the traefik network
# docker network create --driver=bridge traefik-net
version: "3"
services:
    traefik:
        image: traefik
        ports:
            - 8088:8080
            - 80:80
            - 443:443
        networks:
            - traefik-net
        labels:
            - traefik.port=8080
            - traefik.frontend.rule=Host:traefik.airwarrior.net
            - traefik.frontend.auth.basic=admin:$$apr1$$LbMpDV.H$$KOhjvjaXRpztOwF9LgHCa0
        restart: always
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /usr/local/etc/ssl/current:/ssl
        command:
            - --web
            - --docker
            - --docker.domain=airwarrior.net
            - --docker.watch
            - --entrypoints=Name:http Address::80 Redirect.EntryPoint:https
            - --entrypoints=Name:https Address::443 TLS:/ssl/cert.pem,/ssl/key.pem
            - --defaultentrypoints=http,https
            - --logLevel=DEBUG
networks:
    traefik-net:
        external: true
